### ISSUE TITLE
Error:  uninitialized constant Jekyll::SeoTag::JSONLD

### ISSUE THREAD

**Issue by shovanuk** [jekyll/jekyll-seo-tag#193]
I installed Jekyll seo tag plugin. When I ran `jekyll serve` I get the following error

```
jekyll 3.4.3 | Error:  uninitialized constant Jekyll::SeoTag::JSONLD
Did you mean?  JSON
```

Here is the `jekyll build --trace code`
```

jekyll build --trace
Configuration file: /Users/sss/Documents/WebDevelopment/website.org-static/_config.yml
/Users/sss/Documents/WebDevelopment/website.org-static/_plugins/jekyll-seo-tag-master/lib/jekyll-seo-tag/drop.rb:4:in `<class:Drop>': uninitialized constant Jekyll::SeoTag::JSONLD (NameError)
Did you mean?  JSON
	from /Users/sss/Documents/WebDevelopment/website.org-static/_plugins/jekyll-seo-tag-master/lib/jekyll-seo-tag/drop.rb:3:in `<class:SeoTag>'
	from /Users/sss/Documents/WebDevelopment/website.org-static/_plugins/jekyll-seo-tag-master/lib/jekyll-seo-tag/drop.rb:2:in `<module:Jekyll>'
	from /Users/sss/Documents/WebDevelopment/website.org-static/_plugins/jekyll-seo-tag-master/lib/jekyll-seo-tag/drop.rb:1:in `<top (required)>'
	from /Users/sss/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/sss/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/external.rb:43:in `block in require_with_graceful_fail'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/external.rb:40:in `each'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/external.rb:40:in `require_with_graceful_fail'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:73:in `block in require_plugin_files'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:71:in `each'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:71:in `require_plugin_files'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/site.rb:111:in `setup'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/site.rb:33:in `initialize'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:28:in `new'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:28:in `process'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/sss/.rvm/gems/ruby-2.3.3/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
	from /Users/sss/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `load'
	from /Users/sss/.rvm/gems/ruby-2.3.3/bin/jekyll:22:in `<main>'
	from /Users/sss/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sss/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

Can you help?
Thanks

**Comment by benbalter** [comment]
What version of the plugin are you using? This appears to be `master`? How are you including the plugin?

**Comment by DirtyF** [comment]
No response, closing this.
