### ISSUE TITLE
gsub undefined error if title is a number

### ISSUE THREAD

**Issue by BenjaminAbt** [jekyll/jekyll-seo-tag#92]
If I add `{% seo %}` to the head I get this error

```Configuration file: G:/_data/projects/Test/Blog/src/_config.yml
            Source: G:/_data/projects/Test/Blog/src
       Destination: G:/_data/projects/Test/Blog/src/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: undefined method `gsub' for 404:Fixnum in _includes/head.html, included in _layouts/default.html
C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/tags/include.rb:132:in `rescue in render': undefined method `gsub' for 404:Fixnum (Jekyll::Tags::IncludeTagError)
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/tags/include.rb:124:in `render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:106:in `render_liquid'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:146:in `place_in_layouts'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/renderer.rb:70:in `run'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:179:in `block in render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `each'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:177:in `render'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/site.rb:59:in `process'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/command.rb:26:in `process_site'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:60:in `build'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:33:in `process'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/tools/ruby22/lib/ruby/gems/2.2.0/gems/jekyll-3.1.6/bin/jekyll:13:in `<top (required)>'
        from C:/tools/ruby22/bin/jekyll:23:in `load'
        from C:/tools/ruby22/bin/jekyll:23:in `<main>'``` 

I've added all elements to the config as described in the readme.

**Comment by pathawks** [comment]
Is your site source public? I’d like to try to recreate this.

**Comment by BenjaminAbt** [comment]
@pathawks not at this point of time. I'll create a test repo

**Comment by BenjaminAbt** [comment]
@pathawks problem found. I already have a `404.md` in my root folder. After removing this file it works.

**Comment by pathawks** [comment]
I cannot recreate this issue. I wish I could, I'd like to get to the bottom of it.

**Comment by BenjaminAbt** [comment]
I create a repository for u.

**Comment by BenjaminAbt** [comment]
@pathawks here is the sample https://github.com/BenjaminAbt/Jekyll-SEO-gsub-404-error
I have removed all related content but same error all the way.

**Comment by pathawks** [comment]
a-**HA!**

```yaml
---
layout: default
title: 404
---
```

`page.title` is an _integer_ rather than a string, and integers have no `gsub` method.

The quick fix for you is to put quotes around the title:

```yaml
title: "404"
```

The correct fix is for us to make sure we use `to_s` where appropriate. Now I just need to figure out where this is happening...

**Comment by pathawks** [comment]
It appears that when `markdownify` is called on an integer, things break.

I'll kick this upstream.

**Comment by pathawks** [comment]
jekyll/jekyll#4958
